# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XForms-Validate
version:      0.9
version_from: lib/XML/XForms/Validate.pm
installdirs:  site
requires:
    XML::LibXML:                   1.63
    XML::Schema:                   0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
